export default [
  {
    game1: {
      id: 0,
      title: "RODADA 1",
      matchId: 'r1m1',
      date: "DOM. 07/02",
      time: "05:45",
      location: "MARIÁPOLIS",
      home: "Inter",
      away: "Roma",
      homeScore: "0",
      homeScorers: [],
      awayScore: "0",
      awayScorers: [],
      status: "encerrado"
    },
    game2: {
      matchId: 'r1m2',
      date: "DOM. 07/02",
      time: "06:05",
      location: "MARIÁPOLIS",
      home: "Milan",
      away: "Juventus",
      homeScore: "1",
      homeScorers: ['Max'],
      awayScore: "5",
      awayScorers: ['Bertonni', 'Raul', 'Raul', 'Dandão', 'Pedro Henrique'],
      status: "encerrado",
    },
    game3: {
      matchId: 'r1m3',
      date: "DOM. 07/02",
      time: "06:25",
      location: "MARIÁPOLIS",
      home: "Milan",
      away: "Roma",
      homeScore: "1",
      homeScorers: ['Roninho'],
      awayScore: "0",
      awayScorers: [],
      status: "encerrado",
    },
    game4: {
      matchId: 'r1m4',
      date: "DOM. 07/02",
      time: "06:45",
      location: "MARIÁPOLIS",
      home: "Juventus",
      away: "Inter",
      homeScore: "1",
      homeScorers: ['Vitor Sales'],
      awayScore: "1",
      awayScorers: ['Ivson'],
      status: "encerrado",
    },
    game5: {
      matchId: 'r1m5',
      date: "DOM. 07/02",
      time: "07:05",
      location: "MARIÁPOLIS",
      home: "Milan",
      away: "Inter",
      homeScore: "2",
      homeScorers: ['Philip', 'Pequeno'],
      awayScore: "4",
      awayScorers: ['Ivson', 'Henrique', 'Paulinho', 'Deorge B.'],
      status: "encerrado",
    },
    game6: {
      matchId: 'r1m6',
      date: "DOM. 07/02",
      time: "07:25",
      location: "MARIÁPOLIS",
      home: "Juventus",
      away: "Roma",
      homeScore: "2",
      homeScorers: ['Vitor Sales', 'Vitor Sales'],
      awayScore: "1",
      awayScorers: ['Bruninho Jr'],
      status: "encerrado",
    },
  },
  {
    game1: {
      id: 1,
      title: "RODADA 2",
      matchId: 'r2m1',
      date: "DOM. 14/02",
      time: "05:45",
      location: "MARIÁPOLIS",
      home: "Juventus",
      away: "Milan",
      homeScore: "1",
      homeScorers: ['Max'],
      awayScore: "0",
      awayScorers: [],
      status: "encerrado"
    },
    game2: {
      matchId: 'r2m2',
      date: "DOM. 14/02",
      time: "06:05",
      location: "MARIÁPOLIS",
      home: "Inter",
      away: "Roma",
      homeScore: "1",
      homeScorers: ['Deorge B.'],
      awayScore: "0",
      awayScorers: [],
      status: "encerrado",
    },
    game3: {
      matchId: 'r2m3',
      date: "DOM. 14/02",
      time: "06:25",
      location: "MARIÁPOLIS",
      home: "Inter",
      away: "Milan",
      homeScore: "1",
      homeScorers: ['Ivson'],
      awayScore: "0",
      awayScorers: [],
      status: "encerrado",
    },
    game4: {
      matchId: 'r2m4',
      date: "DOM. 14/02",
      time: "06:45",
      location: "MARIÁPOLIS",
      home: "Roma",
      away: "Juventus",
      homeScore: "2",
      homeScorers: ['Emílio', 'Tinho (Bob)'],
      awayScore: "2",
      awayScorers: ['Raul', 'João R.'],
      status: "encerrado",
    },
    game5: {
      matchId: 'r2m5',
      date: "DOM. 14/02",
      time: "07:05",
      location: "MARIÁPOLIS",
      home: "Inter",
      away: "Juventus",
      homeScore: "0",
      homeScorers: [],
      awayScore: "2",
      awayScorers: ['João R.', 'Raul'],
      status: "encerrado",
    },
    game6: {
      matchId: 'r2m6',
      date: "DOM. 14/02",
      time: "07:25",
      location: "MARIÁPOLIS",
      home: "Roma",
      away: "Milan",
      homeScore: "2",
      homeScorers: ['Bruninho Jr', 'Emílio'],
      awayScore: "1",
      awayScorers: ['Marquinhos'],
      status: "encerrado",
    },
  },
  {
    game1: {
      id: 2,
      title: "RODADA 3",
      matchId: 'r3m1',
      date: "DOM. 21/02",
      time: "05:45",
      location: "MARIÁPOLIS",
      home: "Milan",
      away: "Juventus",
      homeScore: "2",
      homeScorers: ['Max', 'Marquinhos'],
      awayScore: "0",
      awayScorers: [],
      status: "encerrado"
    },
    game2: {
      matchId: 'r3m2',
      date: "DOM. 21/02",
      time: "06:05",
      location: "MARIÁPOLIS",
      home: "Roma",
      away: "Inter",
      homeScore: "2",
      homeScorers: ['Nado', 'Juan Felipe'],
      awayScore: "1",
      awayScorers: ['Ivson'],
      status: "encerrado",
    },
    game3: {
      matchId: 'r3m3',
      date: "DOM. 21/02",
      time: "06:25",
      location: "MARIÁPOLIS",
      home: "Roma",
      away: "Juventus",
      homeScore: "3",
      homeScorers: ['Emílio', 'Nado', 'Tinho (Bob)'],
      awayScore: "5",
      awayScorers: ['Vitor Sales', 'Raul', 'Raul', 'Dandão', 'João R.'],
      status: "encerrado",
    },
    game4: {
      matchId: 'r3m4',
      date: "DOM. 21/02",
      time: "06:45",
      location: "MARIÁPOLIS",
      home: "Inter",
      away: "Milan",
      homeScore: "2",
      homeScorers: ['Henrique', 'Gel'],
      awayScore: "4",
      awayScorers: ['Max', 'Philip', 'Roninho', 'Max'],
      status: "encerrado",
    },
    game5: {
      matchId: 'r3m5',
      date: "DOM. 21/02",
      time: "07:05",
      location: "MARIÁPOLIS",
      home: "Roma",
      away: "Milan",
      homeScore: "1",
      homeScorers: ['Juan Felipe'],
      awayScore: "3",
      awayScorers: ['Marquinhos', 'Philip', 'Tarcízio'],
      status: "encerrado",
    },
    game6: {
      matchId: 'r3m6',
      date: "DOM. 21/02",
      time: "07:25",
      location: "MARIÁPOLIS",
      home: "Inter",
      away: "Juventus",
      homeScore: "3",
      homeScorers: ['Ivson', 'Henrique', 'Deorge B.'],
      awayScore: "0",
      awayScorers: [],
      status: "encerrado",
    },
  },
  {
    game1: {
      id: 3,
      title: "RODADA 4",
      matchId: 'r4m1',
      date: "DOM. 28/02",
      time: "05:45",
      location: "MARIÁPOLIS",
      home: "Inter",
      away: "Roma",
      homeScore: "1",
      homeScorers: ['Gel'],
      awayScore: "3",
      awayScorers: ['Bruninho Jr', 'Thiago', 'Pato'],
      status: "encerrado"
    },
    game2: {
      matchId: 'r4m2',
      date: "DOM. 28/02",
      time: "06:05",
      location: "MARIÁPOLIS",
      home: "Juventus",
      away: "Milan",
      homeScore: "4",
      homeScorers: ['Raul', 'Bertonni', 'Vitor Sales', 'Raul'],
      awayScore: "2",
      awayScorers: ['Max', 'Bança'],
      status: "encerrado",
    },
    game3: {
      matchId: 'r4m3',
      date: "DOM. 28/02",
      time: "06:25",
      location: "MARIÁPOLIS",
      home: "Juventus",
      away: "Roma",
      homeScore: "0",
      homeScorers: [],
      awayScore: "3",
      awayScorers: ['Emílio', 'Nado', 'Rato'],
      status: "encerrado",
    },
    game4: {
      matchId: 'r4m4',
      date: "DOM. 28/02",
      time: "06:45",
      location: "MARIÁPOLIS",
      home: "Milan",
      away: "Inter",
      homeScore: "0",
      homeScorers: [],
      awayScore: "3",
      awayScorers: ['Henrique', 'Paulo Có', 'Ivson'],
      status: "em andamento",
    },
    game5: {
      matchId: 'r4m5',
      date: "DOM. 28/02",
      time: "07:05",
      location: "MARIÁPOLIS",
      home: "Juventus",
      away: "Inter",
      homeScore: "1",
      homeScorers: ['Raul'],
      awayScore: "0",
      awayScorers: [],
      status: "encerrado",
    },
    game6: {
      matchId: 'r4m6',
      date: "DOM. 28/02",
      time: "07:25",
      location: "MARIÁPOLIS",
      home: "Milan",
      away: "Roma",
      homeScore: "0",
      homeScorers: [],
      awayScore: "2",
      awayScorers: ['Emílio', 'Emílio'],
      status: "encerrado",
    },
  },
  {
    game1: {
      id: 4,
      title: "RODADA 5",
      matchId: 'r5m1',
      date: "DOM. 04/04",
      time: "05:45",
      location: "MARIÁPOLIS",
      home: "Juventus",
      away: "Roma",
      homeScore: "3",
      homeScorers: ['João R.', 'Dandão', 'Rico'],
      awayScore: "4",
      awayScorers: ['Bruninho Jr', 'Tinho (Bob)', 'Emílio', 'Pato'],
      status: "encerrado"
    },
    game2: {
      matchId: 'r5m2',
      date: "DOM. 04/04",
      time: "06:05",
      location: "MARIÁPOLIS",
      home: "Inter",
      away: "Milan",
      homeScore: "1",
      homeScorers: ['Agushow'],
      awayScore: "2",
      awayScorers: ['Max', 'Marquinhos'],
      status: "encerrado",
    },
    game3: {
      matchId: 'r5m3',
      date: "DOM. 04/04",
      time: "06:25",
      location: "MARIÁPOLIS",
      home: "Roma",
      away: "Milan",
      homeScore: "1",
      homeScorers: ['Emílio'],
      awayScore: "1",
      awayScorers: ['Pequeno'],
      status: "encerrado",
    },
    game4: {
      matchId: 'r5m4',
      date: "DOM. 04/04",
      time: "06:45",
      location: "MARIÁPOLIS",
      home: "Roma",
      away: "Inter",
      homeScore: "3",
      homeScorers: ['Juan Felipe', 'Felipe', 'Thiago'],
      awayScore: "1",
      awayScorers: ['Ivson'],
      status: "encerrado",
    },
    game5: {
      matchId: 'r5m5',
      date: "DOM. 04/04",
      time: "07:05",
      location: "MARIÁPOLIS",
      home: "Juventus",
      away: "Inter",
      homeScore: "0",
      homeScorers: [],
      awayScore: "1",
      awayScorers: ['Ivson'],
      status: "encerrado",
    },
    game6: {
      matchId: 'r5m6',
      date: "DOM. 04/04",
      time: "07:25",
      location: "MARIÁPOLIS",
      home: "Milan",
      away: "Juventus",
      homeScore: "2",
      homeScorers: ['Max', 'Max'],
      awayScore: "2",
      awayScorers: ['Raul', 'Vitor Sales'],
      status: "encerrado",
    },
  },
  {
    game1: {
      id: 5,
      title: "RODADA 6",
      matchId: 'r6m1',
      date: "DOM. 11/04",
      time: "05:45",
      location: "MARIÁPOLIS",
      home: "Inter",
      away: "Milan",
      homeScore: "",
      homeScorers: [],
      awayScore: "",
      awayScorers: [],
      status: "aberto"
    },
    game2: {
      matchId: 'r6m2',
      date: "DOM. 11/04",
      time: "06:05",
      location: "MARIÁPOLIS",
      home: "Juventus",
      away: "Roma",
      homeScore: "",
      homeScorers: [],
      awayScore: "",
      awayScorers: [],
      status: "aberto",
    },
    game3: {
      matchId: 'r6m3',
      date: "DOM. 11/04",
      time: "06:25",
      location: "MARIÁPOLIS",
      home: "Milan",
      away: "Juventus",
      homeScore: "",
      homeScorers: [],
      awayScore: "",
      awayScorers: [],
      status: "aberto",
    },
    game4: {
      matchId: 'r6m4',
      date: "DOM. 11/04",
      time: "06:45",
      location: "MARIÁPOLIS",
      home: "Inter",
      away: "Roma",
      homeScore: "",
      homeScorers: [],
      awayScore: "",
      awayScorers: [],
      status: "aberto",
    },
    game5: {
      matchId: 'r6m5',
      date: "DOM. 11/04",
      time: "07:05",
      location: "MARIÁPOLIS",
      home: "Juventus",
      away: "Inter",
      homeScore: "",
      homeScorers: [],
      awayScore: "",
      awayScorers: [],
      status: "aberto",
    },
    game6: {
      matchId: 'r6m6',
      date: "DOM. 11/04",
      time: "07:25",
      location: "MARIÁPOLIS",
      home: "Roma",
      away: "Milan",
      homeScore: "",
      homeScorers: [],
      awayScore: "",
      awayScorers: [],
      status: "aberto",
    },
  }
]