export default {
  juventus: {
    name: "Juventus",
    captain: "Pedro Henrique",
    formation: '2-2-2',
    played: 15,
    wins: 7,
    draws: 3,
    losses: 5,
    goalsFor: 27,
    goalsAgainst: 25,
    goalDifference: 2,
    points: 24,
    pointsPercentage: 53,
  },
  roma: {
    name: "Roma",
    captain: "Emílio",
    formation: '2-2-2',
    played: 15,
    wins: 7,
    draws: 3,
    losses: 5,
    goalsFor: 27,
    goalsAgainst: 22,
    goalDifference: 5,
    points: 24,
    pointsPercentage: 53,
  },
  milan: {
    name: "Milan",
    captain: "Bança",
    formation: '3-2-1',
    played: 15,
    wins: 5,
    draws: 3,
    losses: 7,
    goalsFor: 18,
    goalsAgainst: 21,
    goalDifference: -3,
    points: 18,
    pointsPercentage: 40,
  },
  inter: {
    name: "Inter",
    captain: "Agushow",
    formation: '2-2-2',
    played: 15,
    wins: 5,
    draws: 3,
    losses: 7,
    goalsFor: 22,
    goalsAgainst: 26,
    goalDifference: -4,
    points: 18,
    pointsPercentage: 40,
  },
}