export default {
  game1: {
    date: "DOM. 04/04",
    time: "05:45",
    location: "MARIÁPOLIS",
    home: "Inter",
    visitor: "Roma",
    homeScore: "1",
    visitorScore: "3",
    status: "encerrado"
  },
  game2: {
    date: "DOM. 04/04",
    time: "06:05",
    location: "MARIÁPOLIS",
    home: "Juventus",
    visitor: "Milan",
    homeScore: "4",
    visitorScore: "2",
    status: "encerrado",
  },
  game3: {
    date: "DOM. 04/04",
    time: "06:25",
    location: "MARIÁPOLIS",
    home: "Juventus",
    visitor: "Roma",
    homeScore: "0",
    visitorScore: "3",
    status: "encerrado",
  },
  game4: {
    date: "DOM. 04/04",
    time: "06:45",
    location: "MARIÁPOLIS",
    home: "Milan",
    visitor: "Inter",
    homeScore: "0",
    visitorScore: "3",
    status: "em andamento",
  },
  game5: {
    date: "DOM. 04/04",
    time: "07:05",
    location: "MARIÁPOLIS",
    home: "Juventus",
    visitor: "Inter",
    homeScore: "1",
    visitorScore: "0",
    status: "encerrado",
  },
  game6: {
    date: "DOM. 04/04",
    time: "07:25",
    location: "MARIÁPOLIS",
    home: "Milan",
    visitor: "Roma",
    homeScore: "0",
    visitorScore: "2",
    status: "encerrado",
  },
}