export default [
  {
    game1: {
      id: 0,
      title: "RODADA 1",
      matchId: 'r1g1',
      date: "DOM. 07/02",
      time: "05:45",
      location: "MARIÁPOLIS",
      home: "Inter",
      visitor: "Roma",
      homeScore: "0",
      visitorScore: "0",
      status: "encerrado"
    },
    game2: {
      matchId: 'r1g2',
      date: "DOM. 07/02",
      time: "06:05",
      location: "MARIÁPOLIS",
      home: "Milan",
      visitor: "Juventus",
      homeScore: "1",
      visitorScore: "5",
      status: "encerrado",
    },
    game3: {
      matchId: 'r1g3',
      date: "DOM. 07/02",
      time: "06:25",
      location: "MARIÁPOLIS",
      home: "Milan",
      visitor: "Roma",
      homeScore: "1",
      visitorScore: "0",
      status: "encerrado",
    },
    game4: {
      matchId: 'r1g4',
      date: "DOM. 07/02",
      time: "06:45",
      location: "MARIÁPOLIS",
      home: "Juventus",
      visitor: "Inter",
      homeScore: "1",
      visitorScore: "1",
      status: "encerrado",
    },
    game5: {
      matchId: 'r1g5',
      date: "DOM. 07/02",
      time: "07:05",
      location: "MARIÁPOLIS",
      home: "Milan",
      visitor: "Inter",
      homeScore: "2",
      visitorScore: "4",
      status: "encerrado",
    },
    game6: {
      matchId: 'r1g6',
      date: "DOM. 07/02",
      time: "07:25",
      location: "MARIÁPOLIS",
      home: "Juventus",
      visitor: "Roma",
      homeScore: "2",
      visitorScore: "1",
      status: "encerrado",
    },
  },
  {
    game1: {
      id: 1,
      title: "RODADA 2",
      matchId: 'r2g1',
      date: "DOM. 14/02",
      time: "05:45",
      location: "MARIÁPOLIS",
      home: "Juventus",
      visitor: "Milan",
      homeScore: "1",
      visitorScore: "0",
      status: "encerrado"
    },
    game2: {
      matchId: 'r2g2',
      date: "DOM. 14/02",
      time: "06:05",
      location: "MARIÁPOLIS",
      home: "Inter",
      visitor: "Roma",
      homeScore: "1",
      visitorScore: "0",
      status: "encerrado",
    },
    game3: {
      matchId: 'r2g3',
      date: "DOM. 14/02",
      time: "06:25",
      location: "MARIÁPOLIS",
      home: "Inter",
      visitor: "Milan",
      homeScore: "1",
      visitorScore: "0",
      status: "encerrado",
    },
    game4: {
      matchId: 'r2g4',
      date: "DOM. 14/02",
      time: "06:45",
      location: "MARIÁPOLIS",
      home: "Roma",
      visitor: "Juventus",
      homeScore: "2",
      visitorScore: "2",
      status: "encerrado",
    },
    game5: {
      matchId: 'r2g5',
      date: "DOM. 14/02",
      time: "07:05",
      location: "MARIÁPOLIS",
      home: "Inter",
      visitor: "Juventus",
      homeScore: "0",
      visitorScore: "2",
      status: "encerrado",
    },
    game6: {
      matchId: 'r2g6',
      date: "DOM. 14/02",
      time: "07:25",
      location: "MARIÁPOLIS",
      home: "Roma",
      visitor: "Milan",
      homeScore: "2",
      visitorScore: "1",
      status: "encerrado",
    },
  },
  {
    game1: {
      id: 2,
      title: "RODADA 3",
      matchId: 'r3g1',
      date: "DOM. 21/02",
      time: "05:45",
      location: "MARIÁPOLIS",
      home: "Milan",
      visitor: "Juventus",
      homeScore: "2",
      visitorScore: "0",
      status: "encerrado"
    },
    game2: {
      matchId: 'r3g2',
      date: "DOM. 21/02",
      time: "06:05",
      location: "MARIÁPOLIS",
      home: "Roma",
      visitor: "Inter",
      homeScore: "2",
      visitorScore: "1",
      status: "encerrado",
    },
    game3: {
      matchId: 'r3g3',
      date: "DOM. 21/02",
      time: "06:25",
      location: "MARIÁPOLIS",
      home: "Roma",
      visitor: "Juventus",
      homeScore: "3",
      visitorScore: "5",
      status: "encerrado",
    },
    game4: {
      matchId: 'r3g4',
      date: "DOM. 21/02",
      time: "06:45",
      location: "MARIÁPOLIS",
      home: "Inter",
      visitor: "Milan",
      homeScore: "2",
      visitorScore: "4",
      status: "encerrado",
    },
    game5: {
      matchId: 'r3g5',
      date: "DOM. 21/02",
      time: "07:05",
      location: "MARIÁPOLIS",
      home: "Roma",
      visitor: "Milan",
      homeScore: "1",
      visitorScore: "3",
      status: "encerrado",
    },
    game6: {
      matchId: 'r3g6',
      date: "DOM. 21/02",
      time: "07:25",
      location: "MARIÁPOLIS",
      home: "Inter",
      visitor: "Juventus",
      homeScore: "3",
      visitorScore: "0",
      status: "encerrado",
    },
  },
  {
    game1: {
      id: 3,
      title: "RODADA 4",
      matchId: 'r4g1',
      date: "DOM. 28/02",
      time: "05:45",
      location: "MARIÁPOLIS",
      home: "Inter",
      visitor: "Roma",
      homeScore: "1",
      visitorScore: "3",
      status: "encerrado"
    },
    game2: {
      matchId: 'r4g2',
      date: "DOM. 28/02",
      time: "06:05",
      location: "MARIÁPOLIS",
      home: "Juventus",
      visitor: "Milan",
      homeScore: "4",
      visitorScore: "2",
      status: "encerrado",
    },
    game3: {
      matchId: 'r4g3',
      date: "DOM. 28/02",
      time: "06:25",
      location: "MARIÁPOLIS",
      home: "Juventus",
      visitor: "Roma",
      homeScore: "0",
      visitorScore: "3",
      status: "encerrado",
    },
    game4: {
      matchId: 'r4g4',
      date: "DOM. 28/02",
      time: "06:45",
      location: "MARIÁPOLIS",
      home: "Milan",
      visitor: "Inter",
      homeScore: "0",
      visitorScore: "3",
      status: "em andamento",
    },
    game5: {
      matchId: 'r4g5',
      date: "DOM. 28/02",
      time: "07:05",
      location: "MARIÁPOLIS",
      home: "Juventus",
      visitor: "Inter",
      homeScore: "1",
      visitorScore: "0",
      status: "encerrado",
    },
    game6: {
      matchId: 'r4g6',
      date: "DOM. 28/02",
      time: "07:25",
      location: "MARIÁPOLIS",
      home: "Milan",
      visitor: "Roma",
      homeScore: "0",
      visitorScore: "2",
      status: "encerrado",
    },
  },
  {
    game1: {
      id: 4,
      title: "RODADA 5",
      matchId: 'r5g1',
      date: "DOM. 04/04",
      time: "05:45",
      location: "MARIÁPOLIS",
      home: "Juventus",
      visitor: "Roma",
      homeScore: "3",
      visitorScore: "4",
      status: "encerrado"
    },
    game2: {
      matchId: 'r5g2',
      date: "DOM. 04/04",
      time: "06:05",
      location: "MARIÁPOLIS",
      home: "Inter",
      visitor: "Milan",
      homeScore: "1",
      visitorScore: "2",
      status: "encerrado",
    },
    game3: {
      matchId: 'r5g3',
      date: "DOM. 04/04",
      time: "06:25",
      location: "MARIÁPOLIS",
      home: "Roma",
      visitor: "Milan",
      homeScore: "1",
      visitorScore: "1",
      status: "encerrado",
    },
    game4: {
      matchId: 'r5g4',
      date: "DOM. 04/04",
      time: "06:45",
      location: "MARIÁPOLIS",
      home: "Roma",
      visitor: "Inter",
      homeScore: "3",
      visitorScore: "1",
      status: "encerrado",
    },
    game5: {
      matchId: 'r5g5',
      date: "DOM. 04/04",
      time: "07:05",
      location: "MARIÁPOLIS",
      home: "Juventus",
      visitor: "Inter",
      homeScore: "0",
      visitorScore: "1",
      status: "encerrado",
    },
    game6: {
      matchId: 'r5g6',
      date: "DOM. 04/04",
      time: "07:25",
      location: "MARIÁPOLIS",
      home: "Milan",
      visitor: "Juventus",
      homeScore: "2",
      visitorScore: "2",
      status: "encerrado",
    },
  },
  {
    game1: {
      id: 5,
      title: "RODADA 6",
      matchId: 'r6g1',
      date: "DOM. 11/04",
      time: "05:45",
      location: "MARIÁPOLIS",
      home: "Inter",
      visitor: "Milan",
      homeScore: "",
      visitorScore: "",
      status: "aberto"
    },
    game2: {
      matchId: 'r6g2',
      date: "DOM. 11/04",
      time: "06:05",
      location: "MARIÁPOLIS",
      home: "Juventus",
      visitor: "Roma",
      homeScore: "",
      visitorScore: "",
      status: "aberto",
    },
    game3: {
      matchId: 'r6g3',
      date: "DOM. 11/04",
      time: "06:25",
      location: "MARIÁPOLIS",
      home: "Milan",
      visitor: "Juventus",
      homeScore: "",
      visitorScore: "",
      status: "aberto",
    },
    game4: {
      matchId: 'r6g4',
      date: "DOM. 11/04",
      time: "06:45",
      location: "MARIÁPOLIS",
      home: "Inter",
      visitor: "Roma",
      homeScore: "",
      visitorScore: "",
      status: "aberto",
    },
    game5: {
      matchId: 'r6g5',
      date: "DOM. 11/04",
      time: "07:05",
      location: "MARIÁPOLIS",
      home: "Juventus",
      visitor: "Inter",
      homeScore: "",
      visitorScore: "",
      status: "aberto",
    },
    game6: {
      matchId: 'r6g6',
      date: "DOM. 11/04",
      time: "07:25",
      location: "MARIÁPOLIS",
      home: "Roma",
      visitor: "Milan",
      homeScore: "",
      visitorScore: "",
      status: "aberto",
    },
  }
]